### PR TITLE
Milestone 2: Creating components

### PR DESCRIPTION
**Pull request by misselliev**

### CODE REVIEW

**Review by SunnyAsar — CHANGES_REQUESTED** [review]
# Hello @misselliev  👋 
Wonderful work, code wise, its looking good.
- For the finish let's make some changes to the repository.
    In accordance with the recent [announcement](https://microverse.zendesk.com/hc/en-us/articles/360039277914-12-2-2019-Professional-Github-repository-lesson)
    - Please add a description to your PR which is supposed to be a summary of what has been done in the milestone, see the [Announcement](https://microverse.zendesk.com/hc/en-us/articles/360039277914-12-2-2019-Professional-Github-repository-lesson) for more.
    - Also update your `readme` to contain information on how to setup the project and remove some of the content e.g. this project does not requires tests, unless you intent to add some testing, it's not needed.

**Please request another review when the changes are done**

**Comment by misselliev** [comment]
React Calculator milestone 2: Components

In this milestone the following changes were implemented:

- Removed unnecessary files
- Updated dependencies to use proptypes
- App component added
- Display component added
- Button component added
- Button Panel component added
- Updated ReadMe file to be more descriptive

**Review by shloch — APPROVED** [review]
## Hello @misselliev 🎅🎅🎅
Great job....
Concerning the informations of your work details you just added in the comments, it could have been done by modifying the PULL REQUEST DESCRIPTION above.

But i know you get the idea now. 

This project is considered valid 

### You can merge this PR...

Happy coding ...... 🎅🎅

**Comment by misselliev** [comment]
Aaah, you're right @shloch! Thank you both so much for your feedback @SunnyAsar @shloch!

**Pull request merged**
